### ISSUE TITLE
#US1203- Quantidade de Horas por Ano

### ISSUE THREAD

**Issue by leticiasalles** [Leo0256/Equipe_Lider-Projeto_GSW#13]
# Quantidade de Horas por Ano
- Colaboradores:

  ||
  |:--|
  | @Leo0256 | 

- User Story:

     > _COMO_ usuário,
     > _DESEJO_ visualizar as horas anuais gastas nos projetos,
     > _PARA_ sugerir tempo gasto em projetos futuros de mesmo complexidade.

- Planning Poker: **`5/100`**
---

**Comment by Leo0256** [comment]
### Resolvido -> [Banco de Dados](https://github.com/Leo0256/Equipe_Lider-Projeto_GSW/blob/main/Arquivos/C%C3%B3digos/GSW_System_code.sql)
