### ISSUE TITLE
#US1303- Quantidade de Horas por Projeto

### ISSUE THREAD

**Issue by leticiasalles** [Leo0256/Equipe_Lider-Projeto_GSW#14]
# Quantidade de Horas por Projeto
- Colaboradores:

  ||
  |:--|
  | @Leo0256 | 

- User Story:

     > _COMO_ usuário,
     > _DESEJO_ visualizar a quantidade de horas por projeto,
     > _PARA_ obter desta forma um parâmetro em projetos futuros com perfis semelhantes. 

- Planning Poker: **`5/100`**
---

**Comment by Leo0256** [comment]
### Resolvido -> [Banco de Dados](https://github.com/Leo0256/Equipe_Lider-Projeto_GSW/blob/main/Arquivos/C%C3%B3digos/GSW_System_code.sql)
