### ISSUE TITLE
#US1403- Porcentagem de dedicação do funcionário por projeto

### ISSUE THREAD

**Issue by leticiasalles** [Leo0256/Equipe_Lider-Projeto_GSW#15]
# Porcentagem de dedicação do funcionário por projeto
- Colaboradores:

  ||
  |:--|
  | @Leo0256 | 

- User Story:

     > _COMO_ usuário,
     > _DESEJO_ visualizar a porcentagem de dedicação de cada funcionário,
     > _PARA_ obter um parâmetro na avaliação individual. 

- Planning Poker: **`5/100`**
---

**Comment by Leo0256** [comment]
### Resolvido -> [Banco de Dados](https://github.com/Leo0256/Equipe_Lider-Projeto_GSW/blob/main/Arquivos/C%C3%B3digos/GSW_System_code.sql)
