### ISSUE TITLE
#US1503- Quantidade de tasks em aberto

### ISSUE THREAD

**Issue by leticiasalles** [Leo0256/Equipe_Lider-Projeto_GSW#16]
# Quantidade de tasks em aberto
- Colaboradores:

  ||
  |:--|
  | @Leo0256 | 

- User Story:

     > _COMO_ usuário,
     > _DESEJO_ visualizar as tasks em aberto,
     > _PARA_ gerenciamento das tarefas de cada projeto. 

- Planning Poker: **`5/100`**
---

**Comment by Leo0256** [comment]
### **Resolvido** -> [Banco de Dados](https://github.com/Leo0256/Equipe_Lider-Projeto_GSW/blob/main/Arquivos/C%C3%B3digos/GSW_System_code.sql)
