### ISSUE TITLE
#US203- Front-end

### ISSUE THREAD

**Issue by Leo0256** [Leo0256/Equipe_Lider-Projeto_GSW#3]
# Front-end
- Colaboradores:

  ||
  |:--|
  | @DanielaMeirelles  | 
  | @MatheusEmboabaTeteu  | 
  | @Glsilva  |
  | @leticiasalles  |
  | @laroyprado  |
  | @Sarah781   | 
  | @Ppistache  |

- User Story:

     > _COMO_ P.O.
     > _DESEJO_ o desenvolvimento da parte visual do sistema, 
     > _PARA_ a interação do usuário com a aplicação

- Planning Poker: **`5/100 **
---

**Comment by leticiasalles** [comment]
Done
