### ISSUE TITLE
#  US303- Identidade Visual

### ISSUE THREAD

**Issue by Leo0256** [Leo0256/Equipe_Lider-Projeto_GSW#4]
# Identidade Visual
- Colaboradores:

  ||
  |:--|
  | @DanielaMeirelles  | 
  | @MatheusEmboabaTeteu  | 
  | @Glsilva  |
  | @leticiasalles  |
  | @laroyprado  |
  | @Sarah781   | 
  | @Ppistache  |

- User Story:

     > _COMO_ P.O.
     > _DESEJO_ a criação e documentação da identidade visual do sistema,
     > _PARA_ a caracterização e melhor estética ao sistema.

- Planning Poker: **`2/100`**
---

**Comment by leticiasalles** [comment]
Done
